### ISSUE TITLE
Verification Problem

### ISSUE THREAD

**Issue by RicardoZhy1215** [GMAP/NPB-GPU#8]
I download this repo and test many problems in A size. I found that all code can not pass verification.

**Comment by dalvangriebler** [comment]
Hi @RicardoZhy1215, could you please provide more details about the problem? We need information about your operating system, CUDA version, and nvidia driver.

**Comment by RicardoZhy1215** [comment]
Hi @dalvangriebler , My OS is ubuntu, cuda version is 12.3 and nvidia driver version is Driver Version: 545.23.08, I use A100 nvidia GPU, thanks for your quick reply!

**Comment by RicardoZhy1215** [comment]
I test all the problem, the final computation is wrong and can not pass the verification. 
![image](https://github.com/GMAP/NPB-GPU/assets/66266662/66154944-0b2f-4fd7-b465-44fe0aad0c2e)

**Comment by dalvangriebler** [comment]
Have you configured correctly the compute capability in the make.def?

**Comment by RicardoZhy1215** [comment]
Hi, @dalvangriebler , no, I just  use the default config in the make.def file.

**Comment by gabriellaraujo1903** [comment]
Hello, Ricardo.

You should update the file make.def by informing the compute capability of your GPU.

You can collect the compute capability of your GPU by running the following command:
´´´
nvidia-smi --query-gpu=compute_cap --format=csv,noheader,nounits
´´´

You must replace the compute capability values in the following line in the make.def file: (in this case, replace 61 by the value of your GPU)
´´´
COMPUTE_CAPABILITY = -gencode arch=compute_61,code=sm_61
´´´

**Comment by RicardoZhy1215** [comment]
hello, Gabriell, many thanks for your help! The problem was solved!
